--------------------------------------------------------
--  File created - Thursday-January-21-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "DELIVERY_SYSTEM"."ADMIN" 
   (	"EMPID" VARCHAR2(20 CHAR), 
	"EMPNAME" VARCHAR2(20 CHAR), 
	"EMPPHONE" VARCHAR2(20 CHAR), 
	"EMPEMAIL" VARCHAR2(50 CHAR), 
	"EMPADDRESS" VARCHAR2(100 CHAR), 
	"EMPUSERNAME" VARCHAR2(20 CHAR), 
	"EMPPASSWORD" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "DELIVERY_SYSTEM"."CUSTOMER" 
   (	"CUSTIC" VARCHAR2(20 CHAR), 
	"CUSTNAME" VARCHAR2(20 CHAR), 
	"CUSTPHONE" VARCHAR2(20 CHAR), 
	"CUSTEMAIL" VARCHAR2(50 CHAR), 
	"CUSTADDRESS" VARCHAR2(100 CHAR), 
	"CUSTUSERNAME" VARCHAR2(20 CHAR), 
	"CUSTPASSWORD" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "DELIVERY_SYSTEM"."MENU" 
   (	"MENUID" VARCHAR2(20 CHAR), 
	"MENUNAME" VARCHAR2(20 CHAR), 
	"PRICE" NUMBER(10,2), 
	"IMAGE" VARCHAR2(60 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "DELIVERY_SYSTEM"."ORDER_DETAILS" 
   (	"ORDERID" VARCHAR2(20 CHAR), 
	"ORDERNAME" VARCHAR2(20 CHAR), 
	"QUANTITY" NUMBER(10,0), 
	"TOTALPRICE" NUMBER(10,2), 
	"CUSTIC" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DELIVERY_SYSTEM.ADMIN
SET DEFINE OFF;
Insert into DELIVERY_SYSTEM.ADMIN (EMPID,EMPNAME,EMPPHONE,EMPEMAIL,EMPADDRESS,EMPUSERNAME,EMPPASSWORD) values ('E01','fatin izzati','01160613641','fatiey@gmail.com','taman cempaka,kuala lumpur','admin','123');
REM INSERTING into DELIVERY_SYSTEM.CUSTOMER
SET DEFINE OFF;
Insert into DELIVERY_SYSTEM.CUSTOMER (CUSTIC,CUSTNAME,CUSTPHONE,CUSTEMAIL,CUSTADDRESS,CUSTUSERNAME,CUSTPASSWORD) values ('990323035036','nur Adriana Aqilah','0123456789','adriana@gmail.com','lorong 12, no 2, taman sri mengkuang,kula lumpur','adriana','123');
REM INSERTING into DELIVERY_SYSTEM.MENU
SET DEFINE OFF;
Insert into DELIVERY_SYSTEM.MENU (MENUID,MENUNAME,PRICE,IMAGE) values ('2','SNACK PLATE COMBO',15.5,'HAI');
Insert into DELIVERY_SYSTEM.MENU (MENUID,MENUNAME,PRICE,IMAGE) values ('3','LOADED POTATO BOWL',15.5,'HAI');
Insert into DELIVERY_SYSTEM.MENU (MENUID,MENUNAME,PRICE,IMAGE) values ('4','AISKRIM',15.5,'HAI');
REM INSERTING into DELIVERY_SYSTEM.ORDER_DETAILS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADMINPK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERY_SYSTEM"."ADMINPK" ON "DELIVERY_SYSTEM"."ADMIN" ("EMPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007592
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERY_SYSTEM"."SYS_C007592" ON "DELIVERY_SYSTEM"."ADMIN" ("EMPPHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007593
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERY_SYSTEM"."SYS_C007593" ON "DELIVERY_SYSTEM"."ADMIN" ("EMPEMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007594
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERY_SYSTEM"."SYS_C007594" ON "DELIVERY_SYSTEM"."ADMIN" ("EMPUSERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERPK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERY_SYSTEM"."CUSTOMERPK" ON "DELIVERY_SYSTEM"."CUSTOMER" ("CUSTIC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007581
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERY_SYSTEM"."SYS_C007581" ON "DELIVERY_SYSTEM"."CUSTOMER" ("CUSTPHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007582
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERY_SYSTEM"."SYS_C007582" ON "DELIVERY_SYSTEM"."CUSTOMER" ("CUSTEMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007583
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERY_SYSTEM"."SYS_C007583" ON "DELIVERY_SYSTEM"."CUSTOMER" ("CUSTUSERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MENUPK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERY_SYSTEM"."MENUPK" ON "DELIVERY_SYSTEM"."MENU" ("MENUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDERPK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERY_SYSTEM"."ORDERPK" ON "DELIVERY_SYSTEM"."ORDER_DETAILS" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" ADD UNIQUE ("EMPUSERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" ADD UNIQUE ("EMPEMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" ADD UNIQUE ("EMPPHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" ADD CONSTRAINT "ADMINPK" PRIMARY KEY ("EMPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" MODIFY ("EMPPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" MODIFY ("EMPUSERNAME" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" MODIFY ("EMPADDRESS" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" MODIFY ("EMPEMAIL" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" MODIFY ("EMPPHONE" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" MODIFY ("EMPNAME" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."ADMIN" MODIFY ("EMPID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" ADD UNIQUE ("CUSTUSERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" ADD UNIQUE ("CUSTEMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" ADD UNIQUE ("CUSTPHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" ADD CONSTRAINT "CUSTOMERPK" PRIMARY KEY ("CUSTIC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" MODIFY ("CUSTPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" MODIFY ("CUSTUSERNAME" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" MODIFY ("CUSTADDRESS" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" MODIFY ("CUSTEMAIL" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" MODIFY ("CUSTPHONE" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" MODIFY ("CUSTNAME" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."CUSTOMER" MODIFY ("CUSTIC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "DELIVERY_SYSTEM"."MENU" ADD CONSTRAINT "MENUPK" PRIMARY KEY ("MENUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELIVERY_SYSTEM"."MENU" MODIFY ("IMAGE" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."MENU" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."MENU" MODIFY ("MENUNAME" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."MENU" MODIFY ("MENUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "DELIVERY_SYSTEM"."ORDER_DETAILS" ADD CONSTRAINT "ORDERPK" PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELIVERY_SYSTEM"."ORDER_DETAILS" MODIFY ("CUSTIC" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."ORDER_DETAILS" MODIFY ("TOTALPRICE" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."ORDER_DETAILS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."ORDER_DETAILS" MODIFY ("ORDERNAME" NOT NULL ENABLE);
  ALTER TABLE "DELIVERY_SYSTEM"."ORDER_DETAILS" MODIFY ("ORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "DELIVERY_SYSTEM"."ORDER_DETAILS" ADD CONSTRAINT "CUSTFK" FOREIGN KEY ("CUSTIC")
	  REFERENCES "DELIVERY_SYSTEM"."CUSTOMER" ("CUSTIC") ENABLE;
